server:
  port: 9521
spring:
  application:
    name: v1-bilibili
  config:
    import: db/mariadb-v1-bilibili.yml
  datasource:
    driver-class-name: ${mariadb.driver-class-name}
    url: ${mariadb.url}
    username: ${mariadb.username}
    password: ${mariadb.password}
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml