server:
  port: 11011
spring:
  application:
    name: sb3-rabbitmq-order
  output:
    ansi:
      enabled: always
  config:
    import: conf/mariadb.yml,conf/mybatis.yml,conf/redis.yml,conf/rabbitmq.yml
