spring:
  datasource:
    mysql:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://${host}:${port.mysql}/testDb?serverTimezone=Asia/Shanghai
      username: root
      password: '123456'