server:
  port: 10010
spring:
  application:
    name: sb3-mybatis3-bigdata
  config:
    import: conf/mysql-hrdb.yml,conf/pgsql-hrdb.yml,
  thymeleaf:
    cache: off
logging:
  level:
    zzjjcc: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: on
