server:
  port: 10010
spring:
  application:
    name: sb3-mybatis3-bigdata
  config:
    # import: conf/mysql.yml,conf/postgresql.yml,conf/maria.yml
    import: conf/maria-multiple-dynamic-datasource.yml,
  thymeleaf:
    cache: off
logging:
  level:
    zzjjcc: debug
    org.springframework.transaction: debug
    org.springframework.jdbc: debug

