server:
  port: 10086
spring:
  application:
    name: RedisSecKill
  thymeleaf:
    enabled: on
    mode: HTML
    cache: off # 开发阶段关闭
    prefix: "classpath:/templates/"
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${mariadb.host}:${mariadb.port}/mariadb10
    username: ${mariadb.username}
    password: ${mariadb.password}
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}
mybatis:
  mapper-locations:
    - "classpath*:/mapper/**/*.xml"
  type-aliases-package: org.zmz.sb3.redis.seckill.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: on