server:
  port: 9522
spring:
  application:
    name: sb3-mybatis3-boot
  datasource:
    eqb:
      username: root
      password: '123456'
      driverClassName: org.mariadb.jdbc.Driver
      jdbcUrl: jdbc:mariadb://localhost:3306/eqbtest?serverTimezone=Asia/Shanghai
    isale:
      username: root
      password: '123456'
      driverClassName: org.mariadb.jdbc.Driver
      jdbcUrl: jdbc:mariadb://localhost:3306/isaletest?serverTimezone=Asia/Shanghai
    esb:
      username: root
      password: '123456'
      driverClassName: org.mariadb.jdbc.Driver
      jdbcUrl: jdbc:mariadb://localhost:3306/esbtest?serverTimezone=Asia/Shanghai
  config:
    import: conf/maria-hrdb.yml