CREATE TABLE `dim_index_info`
(
    `dim_index_id`           bigint(18)  NOT NULL,
    `dim_index_name`         varchar(100)         DEFAULT NULL COMMENT '指标名称',
    `cat_id`                 bigint(18)           DEFAULT NULL COMMENT '指标目录标识',
    `index_code`             varchar(300)         DEFAULT NULL COMMENT '指标编码',
    `meta_table_id`          bigint(18)           DEFAULT NULL COMMENT '指标所在目标表标识',
    `src_type`               varchar(50)          DEFAULT NULL COMMENT '指标来源类型',
    `table_code`             varchar(100)         DEFAULT NULL COMMENT '指标所在目标表编码',
    `field_code`             varchar(50)          DEFAULT NULL COMMENT '指标所在目标表字段编码',
    `index_wide_col_seq`     varchar(10)          DEFAULT NULL COMMENT '指标所在目标表字段顺序',
    `index_cycle`            varchar(4)           DEFAULT NULL COMMENT '指标周期类型',
    `state`                  varchar(10)          DEFAULT NULL COMMENT '指标状态',
    `dim_index_busi_desc`    text COMMENT '指标业务口径',
    `dim_index_tech_desc`    text COMMENT '指标技术口径',
    `dim_index_desc`         text COMMENT '指标描述',
    `create_staff`           bigint(18)           DEFAULT NULL COMMENT '指标名称',
    `index_modify_date`      datetime             DEFAULT NULL COMMENT '指标修改时间',
    `com_acct_id`            bigint(18)           DEFAULT NULL COMMENT '指标企业标识',
    `order_no`               varchar(18)          DEFAULT NULL COMMENT '指标审批工单号',
    `FIELD_DATA_TYPE`        varchar(10)          DEFAULT NULL,
    `DEFAULT_VALUE`          varchar(50)          DEFAULT NULL,
    `INDEX_TYPE`             tinyint(4)           DEFAULT NULL,
    `EFF_DATE`               datetime(6)          DEFAULT NULL,
    `EXP_DATE`               datetime(6)          DEFAULT NULL,
    `CREATE_DATE`            datetime(6)          DEFAULT NULL,
    `create_staff_code`      varchar(60)          DEFAULT NULL COMMENT '工号',
    `DATA_SRC_COL_NAME`      text,
    `ATTR_CODE`              varchar(100)         DEFAULT NULL,
    `order_id`               bigint(18)           DEFAULT NULL,
    `dim_index_type`         varchar(30)          DEFAULT NULL,
    `dim_index_used_area`    varchar(30)          DEFAULT NULL,
    `dim_index_unit`         varchar(50)          DEFAULT NULL,
    `dim_index_version`      varchar(50)          DEFAULT NULL,
    `DATA_SCOPE`             varchar(300)         DEFAULT NULL,
    `IS_DESENSITIZED`        varchar(300)         DEFAULT NULL,
    `DESENSITIZED_ALGORITHM` varchar(300)         DEFAULT NULL,
    `RELEASE_AREA`           varchar(300)         DEFAULT NULL,
    `SRC_SYSTEM`             varchar(300)         DEFAULT NULL,
    `SRC_DATABASE`           varchar(300)         DEFAULT NULL,
    `INJECT_POINT_TYPE`      varchar(300)         DEFAULT NULL,
    `GEN_TIME`               varchar(300)         DEFAULT NULL,
    `GEN_SCRIPT`             varchar(300)         DEFAULT NULL,
    `DATA_SRC_COL_VALUE`     varchar(100)         DEFAULT NULL,
    `SUBJECT_CODE`           varchar(100)         DEFAULT NULL,
    `PRO_INDEX_ID`           bigint(20)           DEFAULT '-1' COMMENT '原子指标标识',
    `PRO_CYCLE_ID`           bigint(20)           DEFAULT '-1' COMMENT '统计周期',
    `PRO_RESTRICT_ID`        bigint(20)           DEFAULT '-1' COMMENT '业务限定',
    `PRO_COLUMN_ID`          bigint(20)           DEFAULT '-1' COMMENT '业务限定',
    `PRO_TABLE_ID`           bigint(20)           DEFAULT '-1' COMMENT '业务过程标识',
    `UPDATE_DATE`            datetime             DEFAULT NULL,
    `TAR_TABLE_CODE`         varchar(60)          DEFAULT NULL,
    `UPDATE_STAFF`           varchar(20)          DEFAULT NULL,
    `index_source_sys`       varchar(100)         DEFAULT NULL,
    `index_app_path`         varchar(500)         DEFAULT NULL,
    `cal_method`             varchar(5)           DEFAULT NULL,
    `is_new_table`           varchar(5)           DEFAULT NULL,
    `input_table`            varchar(200)         DEFAULT NULL,
    `output_table`           varchar(200)         DEFAULT NULL,
    `lat`                    varchar(500)         DEFAULT NULL,
    `bus_model_id`           varchar(20)          DEFAULT NULL,
    `index_org_type`         varchar(10)          DEFAULT NULL COMMENT '指标组织类型',
    `index_particle`         varchar(50)          DEFAULT NULL COMMENT '指标粒度',
    `index_table_name`       varchar(200)         DEFAULT NULL COMMENT '指标所在小指标表',
    `index_column_name`      varchar(100)         DEFAULT NULL COMMENT '指标所在字段',
    `index_wide_table_name`  varchar(200)         DEFAULT NULL COMMENT '目标指标的宽表表名',
    `index_submit_org`       varchar(20)          DEFAULT NULL,
    `index_inf_man`          varchar(20)          DEFAULT NULL COMMENT '指标接口人',
    `index_inf_phone`        varchar(20)          DEFAULT NULL COMMENT '接口人联系电话',
    `index_finish_day`       varchar(50)          DEFAULT NULL COMMENT '指标正常出数时间（日）',
    `index_finish_hour`      varchar(50)          DEFAULT NULL COMMENT '指标正常出数时间（小时',
    `index_finish_minute`    varchar(50)          DEFAULT NULL COMMENT '指标正常出数时间（分钟）',
    `src_datasource`         varchar(200)         DEFAULT NULL COMMENT '数据源来源',
    `src_schema_code`        varchar(100)         DEFAULT NULL COMMENT '来源数据源所在库',
    `start_date`             varchar(50)          DEFAULT NULL COMMENT '生效时间',
    `end_date`               varchar(50)          DEFAULT NULL COMMENT '失效时间',
    `index_dev_man`          varchar(50)          DEFAULT NULL,
    `dimension_code_set`     varchar(150)         DEFAULT NULL,
    `key_words`              varchar(100)         DEFAULT NULL,
    `app_id`                 varchar(20)          DEFAULT NULL COMMENT '视图取数id',
    `service_id`             bigint(20)           DEFAULT NULL,
    `COMMON_RESTRICT_ID`     bigint(20)           DEFAULT NULL COMMENT '公共限定ID',
    `COLUMN_ID`              int(9)               DEFAULT NULL COMMENT '字段ID',
    `cycle_id`               bigint(20)           DEFAULT NULL COMMENT '周期ID',
    `CREATE_STAFF_NAME`      varchar(50)          DEFAULT NULL COMMENT '创建人名称',
    `SRC_TABLE`              varchar(200)         DEFAULT NULL COMMENT '输入宽表',
    `datasource_id`          bigint(18)           DEFAULT NULL COMMENT '数据源ID',
    `DIM_INDEX_SRC`          varchar(3)           DEFAULT NULL COMMENT '指标来源',
    `VERSION`                varchar(10)          DEFAULT NULL COMMENT '版本号',
    `dim_column_ids`         varchar(500)         DEFAULT NULL COMMENT '统计粒度编码（多个拼接）',
    `object_id`              bigint(20)           DEFAULT NULL COMMENT '对象标识',
    `status_open`            varchar(10)          DEFAULT NULL COMMENT '开放状态',
    `project_id`             bigint(18)           DEFAULT NULL COMMENT '项目ID',
    `pro_restrict_version`   varchar(10)          DEFAULT NULL COMMENT '业务限定版本号',
    `dim_standard_code`      varchar(128)         DEFAULT NULL COMMENT '指标标准编码',
    `create_type`            varchar(10) NOT NULL DEFAULT 'DERIVE' COMMENT '指标类型，DERIVE: 派生指标；COMPLEX：复合指标',
    `complex_type`           varchar(10)          DEFAULT NULL COMMENT '复合指标类型，目前只有净增量GROWTH',
    `derive_index_id`        bigint(20)           DEFAULT NULL COMMENT '派生指标ID，即复合指标对应的派生指标ID',
    `cycle_step`             int(11)              DEFAULT NULL COMMENT '净增量指标的账期步长',
    PRIMARY KEY (`dim_index_id`) USING BTREE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  ROW_FORMAT = COMPACT;
