server:
  port: 9082
spring:
  application:
    name: sb3-netty-chat-ch3
  config:
    import: conf/abc.yml
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: '*'