spring:
  datasource:
    maria:
      hrdb:
        driverClassName: org.mariadb.jdbc.Driver
        jdbcUrl: jdbc:mariadb://localhost:3306/hrdb
        username: root
        password: '123456'
      mytest:
        driverClassName: org.mariadb.jdbc.Driver
        jdbcUrl: jdbc:mariadb://localhost:3306/mytest
        username: root
        password: '123456'
logging:
  level:
    zzjjcc.mapper.mariadb.hrdb: debug
    zzjjcc.mapper.mariadb.mytest: debug