spring:
  datasource:
    dynamic:
      primary: master
      ds:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          driverClassName: org.mariadb.jdbc.Driver
          url: jdbc:mariadb://localhost:3306/hrdb?serverTimezone=Asia/Shanghai
          username: root
          password: '123456'
        esb:
          type: com.alibaba.druid.pool.DruidDataSource
          driverClassName: org.mariadb.jdbc.Driver
          url: jdbc:mariadb://localhost:3306/esb?serverTimezone=Asia/Shanghai
          username: root
          password: '123456'
        eqb:
          type: com.alibaba.druid.pool.DruidDataSource
          driverClassName: org.mariadb.jdbc.Driver
          url: jdbc:mariadb://localhost:3306/eqb?serverTimezone=Asia/Shanghai
          username: root
          password: '123456'