spring:
  datasource:
    mysql:
      hrdb:
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/hrdb?serverTimezone=Asia/Shanghai
        username: root
        password: '123456'

mybatis:
  configuration:
    mysql:
     map-underscore-to-camel-case: on