env:
  jdbcUrl: jdbc:mysql://172.29.71.176:3316/mytest?serverTimezone=Asia/Shanghai
  username: root
  password: 123456

spring:
  datasource:
    mysql:
      hrdb:
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: ${env.jdbcUrl}
        username: ${env.username}
        password: ${env.password}

mybatis:
  configuration:
    mysql:
      hrdb:
        map-underscore-to-camel-case: on