spring:
  datasource:
    pgsql:
      hrdb:
        driverClassName: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://localhost:5432/hrdb
        username: postgres
        password: '123456'

mybatis:
  configuration:
    pgsql:
      map-underscore-to-camel-case: on